digifoot/api/apps/league/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from django.views.decorators.cache import cache_page

from digifoot.api.apps.league.resources import MatchResource
from digifoot.api.apps.league.views import StartMatchView, IndexView, PreviewMatchView, CancelMatchView, \
    FinalResultsMatchView, ChangeSidesView, QuickStartView, CreditsView, StatsView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^new/(?P<players_num>2|4)/$', StartMatchView.as_view(), name="new"),
    url(r'^preview/$', PreviewMatchView.as_view(), name="preview"),
    url(r'^cancel/$', CancelMatchView.as_view(), name="cancel"),
    url(r'^final_results/$', FinalResultsMatchView.as_view(), name="final_results"),
    url(r'^change_sides/$', ChangeSidesView.as_view(), name="change_sides"),
    url(r'^quick_start/$', QuickStartView.as_view(), name="quick_start"),
    url(r'^credits/$', CreditsView.as_view(), name="credits"),
    url(r'^stats/$', cache_page(2)(StatsView.as_view()), name="stats"),

    # API
    url(r'^matches/current/$', cache_page(2)(MatchResource.as_view()), name="current"),
]

digifoot/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url, include, patterns
from django.contrib import admin
from django.views.generic.base import RedirectView
from rest_framework.urlpatterns import format_suffix_patterns

from django.conf import settings

handler500 = 'digifoot.lib.resources.handler500'


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('digifoot.api.apps.league.urls', namespace="league")),
    url(r'^users/', include('digifoot.api.apps.users.urls')),
    url(r'^sparks/', include('digifoot.api.apps.sparks.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + format_suffix_patterns([
])

# Debug
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

digifoot/api/apps/league/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import logging

from django.db.models.fields import CharField, BooleanField, DateTimeField
from django.db.models.fields.related import ForeignKey, ManyToManyField
from django.utils import timezone
from twitter.error import TwitterError

from digifoot.api.apps.sparks.models import SparkDeviceModel
from digifoot.lib.django.models import AbstractModel


log = logging.getLogger(__name__)


class PlayerModel(AbstractModel):
    name = CharField(unique=True, max_length=255, null=False, blank=False)


class MatchModel(AbstractModel):
    class WrongPlayers(Exception):
        pass

    class MatchAlreadyInProgress(Exception):
        pass

    class Meta:
        index_together = ('device', 'finished', )

    device = ForeignKey(SparkDeviceModel, related_name="matches", db_index=True)
    finished = BooleanField(default=False, db_index=True)
    finished_at = DateTimeField(blank=False, default=timezone.now)

    tweeted = BooleanField(default=False)
    canceled = BooleanField(default=False)

    white_side_players = ManyToManyField(PlayerModel, related_name="white_side_players")
    black_side_players = ManyToManyField(PlayerModel, related_name="black_side_players")

    @property
    def duration(self):
        return self.finished_at - self.created_at

    def cancel(self):
        self.device.reset_state()
        self.device.pusher_send_match_changed()

        self.canceled = True
        self.save()

    def finish(self):
        self.device.reset_state()

        self.finished = True
        self.finished_at = timezone.now()
        self.save()

        self.tweet_if_needed()

    @property
    def team_names(self):
        if self.white_count > self.black_count:
            winners = self.white_side_players
            losers = self.black_side_players
        else:
            winners = self.black_side_players
            losers = self.white_side_players

        winners_names = [winner.name for winner in winners.all()]
        losers_names = [loser.name for loser in losers.all()]
        return winners_names, losers_names

    @property
    def final_scores(self):
        if self.white_count > self.black_count:
            winners = self.white_count
            losers = self.black_count
        else:
            winners = self.black_count
            losers = self.white_count

        return winners, losers

    @property
    def tweet_message(self):

        winners, losers = self.team_names

        easter_egg = set(winners + losers) == set(["mfts0", "_strobl", "bartoszhernas", "michal.hernas"])

        winners = " ".join(["@{0}".format(w) for w in winners])
        losers = " ".join(["@{0}".format(l) for l in losers])

        winners_score, losers_score = self.final_scores

        status = "#{pk} Schönes Ding: {winners} gewinnt {winners_score}:{losers_score} gegen {losers}".format(
            winners=winners,
            winners_score=winners_score,
            losers_score=losers_score,
            losers=losers,
            pk=self.pk
        )

        if easter_egg:
            status = "Piękna rzecz: {winners} wygrali {winners_score}:{losers_score} z {losers} #hernas #hackevents".format(
                winners=winners,
                winners_score=winners_score,
                losers_score=losers_score,
                losers=losers,
            )

        return status

    def tweet_if_needed(self):
        if not self.tweeted:
            try:
                result = self.device.twitter_api.PostUpdate(self.tweet_message)

                self.tweeted = True
                self.save()
            except TwitterError:
                pass


    @classmethod
    def create_match(cls, spark, white_player1, black_player1, white_player2=None, black_player2=None):
        if cls.last_match(spark) is not None:
            raise cls.MatchAlreadyInProgress()

        if white_player1 is None or black_player1 is None:
            raise cls.WrongPlayers()

        match = MatchModel()
        match.device = spark
        match.save()

        match.white_side_players.add(white_player1)
        match.black_side_players.add(black_player1)

        if white_player2:
            match.white_side_players.add(white_player2.pk)
        if black_player2:
            match.black_side_players.add(black_player2)

        match.device.reset_state()
        match.device.pusher_send_match_changed()
        return match

    @classmethod
    def last_match(cls, spark):
        return cls.objects.filter(device=spark, finished=False, canceled=False).last()

    @property
    def white_count(self):
        return self.goals.filter(whites=True).count()

    @property
    def black_count(self):
        return self.goals.filter(whites=False).count()

    def send_to_pusher(self):
        self.device.pusher_send_goal(self.white_count, self.black_count, self.finished)


class GoalModel(AbstractModel):
    match = ForeignKey(MatchModel, related_name="goals")
    whites = BooleanField()

    @classmethod
    def do_score(cls, spark, whites):
        goal = GoalModel()
        goal.match = MatchModel.last_match(spark)
        goal.whites = whites
        goal.save()
        return goal

digifoot/api/apps/league/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import logging
from django import forms

log = logging.getLogger(__name__)

class StartMatchForm(forms.Form):
    player1_white = forms.CharField(label='Player 1', max_length=255)
    player2_white = forms.CharField(label='Player 2', max_length=255, required=False)
    player1_black = forms.CharField(label='Player 1', max_length=255)
    player2_black = forms.CharField(label='Player 2', max_length=255, required=False)

digifoot/api/apps/league/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import logging
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.views.generic.base import View, TemplateView
from digifoot.api.apps.league.forms import StartMatchForm
from digifoot.api.apps.league.models import MatchModel, PlayerModel

log = logging.getLogger(__name__)


class IndexView(TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        if MatchModel.last_match(request.spark):
            return redirect(reverse('league:preview'))

        return self.render_to_response({})



class CreditsView(TemplateView):
    template_name = "credits.html"

class StartMatchView(TemplateView):
    template_name = "startmatch.html"

    def get(self, request, players_num, *args, **kwargs):
        if MatchModel.last_match(request.spark):
            return redirect(reverse('league:preview'))

        return self.render_to_response({"form": StartMatchForm(), "four_players": players_num == '4'})

    def post(self, request, *args, **kwargs):
        form = StartMatchForm(self.request.POST)
        if form.is_valid():
            player1_white, _ = PlayerModel.objects.get_or_create(name=form.cleaned_data['player1_white'])
            player2_white = form.cleaned_data['player2_white']

            player1_black, _ = PlayerModel.objects.get_or_create(name=form.cleaned_data['player1_black'])
            player2_black = form.cleaned_data['player2_black']

            if player2_black:
                player2_black, _ = PlayerModel.objects.get_or_create(name=player2_black)
            else:
                player2_black = None

            if player2_white:
                player2_white, _ = PlayerModel.objects.get_or_create(name=player2_white)
            else:
                player2_white = None

            try:
                match = MatchModel.create_match(request.spark, player1_white, player1_black, player2_white,
                                                player2_black)
                return redirect(reverse('league:preview'))

            except MatchModel.WrongPlayers:
                error = "You need minimum two players, one for each team."
            except MatchModel.MatchAlreadyInProgress:
                error = "Match is already in progress"

        return self.render_to_response({"form": form})


class PreviewMatchView(TemplateView):
    template_name = "preview.html"

    def get(self, request, *args, **kwargs):
        match = MatchModel.last_match(request.spark)
        if not match:
            return redirect(reverse('league:index'))

        return self.render_to_response({"match": match, "spark": request.spark})

class CancelMatchView(View):

    def get(self, request, *args, **kwargs):
        match = MatchModel.objects.filter(device=request.spark).last()
        match.cancel()

        return redirect(reverse('league:index'))

class FinalResultsMatchView(TemplateView):
    template_name = "finalresults.html"

    def get(self, request, *args, **kwargs):
        match = MatchModel.objects.filter(device=request.spark, finished=True).last()
        return self.render_to_response({"match": match})

class ChangeSidesView(View):

    def get(self, request, *args, **kwargs):
        old_match = MatchModel.objects.filter(device=request.spark, finished=True).last()
        old_match.cancel()

        match = MatchModel.last_match(request.spark)
        if match:
            return redirect(reverse('league:preview'))

        white_players = old_match.white_side_players.all()
        black_players = old_match.black_side_players.all()

        wp1 = white_players[0]
        bp1 = black_players[0]

        wp2 = white_players[1] if len(white_players) > 1 else None
        bp2 = black_players[1] if len(black_players) > 1 else None

        MatchModel.create_match(request.spark, bp1, wp1, bp2, wp2)
        return redirect(reverse('league:preview'))

class QuickStartView(View):

    def get(self, request, *args, **kwargs):
        match = MatchModel.last_match(request.spark)
        if match:
            return redirect(reverse('league:preview'))

        team1, _= PlayerModel.objects.get_or_create(name="Team 1")
        team2, _ = PlayerModel.objects.get_or_create(name="Team 2")

        MatchModel.create_match(request.spark, team1, team2)
        return redirect(reverse('league:preview'))



class StatsView(TemplateView):
    template_name = "stats/index.html"

    def get(self, request, *args, **kwargs):
        return self.render_to_response({
            'matches': MatchModel.objects.filter(device=request.spark, finished=True).order_by('-finished_at').all()[0:50]
        })

digifoot/api/apps/league/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Digital Foosball</title>

    <!-- Bootstrap -->
{#    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">#}
    <link href="{% static 'css/mobileapp.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>



  <script src="https://js.pusher.com/3.0/pusher.min.js"></script>
  <script>
    // Enable pusher logging - don't include this in production
    Pusher.log = function (message) {
      if (window.console && window.console.log) {
        window.console.log(message);
      }
    };

    var pusher = new Pusher('{{ request.spark.PUSHER_PUBLIC }}', {
      cluster: '{{ request.spark.PUSHER_CLUSTER }}',
      encrypted: true
    });


    var channel = pusher.subscribe('{{ request.spark.pusher_channel_name }}');
    channel.bind('match-changed', function(data) {
      window.location.href = '{% url 'league:index' %}';
    });
  </script>

  </head>
  <body>

    {% block main %}{% endblock %}


  <div class="footer">
  <p><a href="{% url 'league:stats' %}">Look at the STATISTICS</a></p>
    <p>Crafted specially for
      {% if request.spark.org_name %}
        <strong>{{ request.spark.org_name }}</strong>
      {% else %}
      <img src="{% static 'images/twitter_logo.png' %}" />
      {% endif %}
     by 
    </p>
  <p><a href="http://buildmethisapp.com">Build Me This App</a>
  </p>
    <sub style="color: #666">#{{ request.spark.spark_id }}</sub>
  </div>

    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </body>
</html>

digifoot/api/apps/league/templates/bootstrap_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Digital Foosball</title>

  <!-- Bootstrap -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
  <link href="{% static 'css/stats.css' %}" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
{% block header %}
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'league:index' %}">Digital Foosball</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'league:stats' %}">Statistics</a></li>
        <li class=""><a href="{% url 'league:new' players_num=2 %}">New 2 vs 2</a></li>
        <li class=""><a href="{% url 'league:new' players_num=4 %}">New 4 vs 4</a></li>
        <li class=""><a href="{% url 'league:credits' %}">Credits</a></li>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>
{% endblock %}

<div class="container">

  <div class="starter-template">
    {% block main %}{% endblock %}
  </div>
</div>
<!-- /.container -->


<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

digifoot/api/apps/league/templates/credits.html
{% extends 'bootstrap_base.html' %}
{% block header %}
{% endblock %}
{% block main %}
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg=="
        crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw=="
        crossorigin="anonymous">
  <div class="credits">
    <div class="text-center">
      <h1>Project crafted with <i class="fa fa-heart"></i> in Berlin</h1>

      <h2>Contributors: </h2>

      <p></p><a href="http://b.hern.as">Bartosz Hernas</a></p>


      <p><a href="http://buildmethisapp.com">Christian Strobl</a></p>

      <p><a href="http://buildmethisapp.com">Marc Seitz</a></p>

      <p><a href="http://m.hern.as">Michał Hernas</a></p>

      <h2>Check out: </h2>

      <p><a href="http://buildmethisapp.com">Build Me This App</a></p>

      <p><a href="http://hern.as">Hern.as</a></p>
    </div>

  </div>
{% endblock %}

digifoot/api/apps/league/templates/finalresults.html
{% extends 'base.html' %}
{%  load naturalTimeDifference %}
{% block main %}


        <!-- FINAL RESULTS -->
		<section id="summary" class="page active">
			<div class="toolbar">
				<h1>Digital Foosball</h1>
			</div>
			<h2 class="h1">Spielende nach <span class="js_duration">{{ match.duration | naturalTimeDifference }}</span></h2>
			<p class="h1">Endstand <span class="js_finalscore">{{ match.white_count }}:{{ match.black_count }}</span></p>
			<div class="tweet js_tweet"><span>Tweet wird gesendet...</span></div>

			<!-- CANCEL + NEW GAME -->
			<div class="buttonbar">
				<a href="{% url 'league:change_sides' %}" class="button js_rematch">Seitenwechsel</a>
				<a href="{% url 'league:cancel' %}" class="button js_quit">Abbruch</a>
			</div>
		</section>
{% endblock %}

digifoot/api/apps/league/templates/index.html
{% extends 'base.html' %}
{% block main %}
  <!-- START -->
  <section id="home" class="page active">
    <div class="toolbar">
      <h1>Digital Foosball</h1>
    </div>
    <h2 class="h1">Willkommen beim DIGITAL FOOSBALL</h2>

    <p>Lust auf ein Spiel?</p>
    <ul id="gametypes">
      <li class="two"><a href="{% url 'league:new' 2 %}" class="js_login" data-opponents="2">1 Gegen 1</a></li>
      <li class="four"><a href="{% url 'league:new' 4 %}">2 Gegen 2</a></li>
      <li class="quick"><a href="{% url 'league:quick_start' %}" class="js_quickstart">Quickstart</a></li>
    </ul>
  </section>
{% endblock %}

digifoot/api/apps/league/templates/preview.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
  <script type="application/javascript" src="{% static "js/scoreboard.js" %}"></script>
  <script type="application/javascript">
    var final_results_url = "{% url 'league:final_results' %}";
    $(document).ready(function () {
      scored("{{ match.white_count }}", "{{ match.black_count }}");
    });

    var channel = pusher.subscribe('{{ spark.pusher_channel_name }}');
    channel.bind('goal', function(data) {
      refreshScores(data.white_goals, data.black_goals, data.finished);
    });
  </script>

  <section id="container">

    <!-- SCORE -->

    <section id="scoreboard" class="page active">
      <div class="toolbar">
{#        <a href="#settings" class="settings js_setup">⚙</a>#}
{#        <a href="#scoreboard" class="undo hide js_undo">Undo</a>#}

        <h1>Digital Foosball</h1>
        <a href="{% url 'league:cancel' %}" class="cancel js_abort">Abbruch</a>
      </div>
      <dl class="board">
        <dt>Weiss</dt>
        <dd id="scorehome" class="scorecard full">&nbsp;</dd>
        <dt>Schwarz</dt>
        <dd id="scorevisitors" class="scorecard full">&nbsp;</dd>
      </dl>
      <div class="players show" style="display: block;">
        <div>
          <div class="formrow">
            <div class="home1">{{ match.white_side_players.all.0.name }}</div>
            <div class="home2">{{ match.white_side_players.all.1.name }}</div>
          </div>
          <div class="formrow">
            <div class="visitors1">{{ match.black_side_players.all.0.name }}</div>
            <div class="visitors2">{{ match.black_side_players.all.1.name }}</div>
          </div>
        </div>
      </div>
{#         <div class="settings active">#}
{#            <a href="#settings" class="btn change js_invert">⇔</a>#}
{#            <a href="#settings" class="btn home plus js_homeplus">▲</a>#}
{#            <a href="#settings" class="btn home minus js_homeminus">▼</a>#}
{#            <a href="#settings" class="btn visitors plus js_visitorsplus">▲</a>#}
{#            <a href="#settings" class="btn visitors minus js_visitorsminus">▼</a>#}
{#        </div>#}
    </section>

  </section>{% endblock %}

digifoot/api/apps/league/templates/startmatch.html
{% extends 'base.html' %}
{% block main %}


		<!-- SECTION LOGIN -->
		<section id="login" class="page active">
			<div class="toolbar">
				<a href="{% url 'league:index' %}" class="back js_home">Home</a>
				<h1>Digital Football</h1>
			</div>
			<h2 class="h1">Gib die Usernamen der Spieler ein.</h2>
			<p>Usernamen mit @ werden als Twitternamen erkannt.</p>
<form action="" method="post"  novalidate="novalidate">
    {% csrf_token %}
				<fieldset>
					<div class="formrow">
						<div><input type="email" name="player1_white" /></div>
            {%  if four_players %}
						<div><input type="email" name="player2_white" /></div>
            {% endif %}
					</div>
					<div class="formrow">
						<div><input type="email" name="player1_black" /></div>
            {%  if four_players %}
						<div><input type="email" name="player2_black" /></div>
            {% endif %}
					</div>
				</fieldset>
                <div class="buttonbar">
                    <input type="submit" class="button" value="Los geht's" />
                </div>
			</form>
		</section>
{% endblock %}